import type { Language } from '../i18n.ts';

const copy = {
  ru: {
    selectMany: 'Объединить портфели',
    group: 'Группа',
    crypto: 'Криптовалюты',
    showSelection: 'Показать выбранные',
    selectionHelp: 'Выберите хотя бы один портфель.',
    account: 'Счёт',
    addAccount: 'Добавить счёт',
    addGroup: 'Создать группу',
    edit: 'Изменить',
    archive: 'В архив',
    delete: 'Удалить',
    details: 'Подробнее',
    manage: 'Управление',
    entitySaved: 'Это пример. Изменения не сохранены.',
    filter: 'Фильтры операций',
    search: 'Поиск',
    searchHint: 'Актив, портфель или заметка',
    type: 'Тип операции',
    allTypes: 'Все типы',
    allAssets: 'Все активы',
    asset: 'Актив',
    from: 'С даты',
    to: 'До даты',
    order: 'Порядок',
    newest: 'Сначала новые',
    oldest: 'Сначала старые',
    reset: 'Сбросить фильтры',
    empty: 'Операций по фильтрам нет',
    dateError: 'Начало периода должно быть не позже конца.',
    count: 'Найдено операций',
    note: 'Покупки входят в расчёт. Остальные строки — примеры форм, они не меняют результат.',
    sample: 'Пример формы · не включён в результат',
    actual: 'Учебная покупка · включена в расчёт',
    transaction: 'Операция',
    amount: 'Сумма',
    spent: 'Списано',
    received: 'Получено',
    source: 'Источник записи',
    externalSource: 'Внешний источник',
    externalDestination: 'Внешнее назначение',
    bank: 'Учебный банковский счёт',
    destination: 'Получатель',
    comment: 'Заметка',
    example: 'Вымышленный пример',
    deleteTitle: 'Удалить операцию?',
    confirmDelete: 'Подтверждаю удаление примера',
    deleteNote: 'В настоящем учёте это изменит остатки и результат. В макете строка останется.',
    displayed: 'Показаны фиксированные примеры',
    accounts: 'Счета и группы',
    groupName: 'Криптовалюты',
  },
  en: {
    selectMany: 'Combine portfolios',
    group: 'Group',
    crypto: 'Crypto',
    showSelection: 'Show selection',
    selectionHelp: 'Select at least one portfolio.',
    account: 'Account',
    addAccount: 'Add account',
    addGroup: 'Create group',
    edit: 'Edit',
    archive: 'Archive',
    delete: 'Delete',
    details: 'Details',
    manage: 'Manage',
    entitySaved: 'This is a sample. Changes were not saved.',
    filter: 'Transaction filters',
    search: 'Search',
    searchHint: 'Asset, portfolio or note',
    type: 'Transaction type',
    allTypes: 'All types',
    allAssets: 'All assets',
    asset: 'Asset',
    from: 'From date',
    to: 'To date',
    order: 'Order',
    newest: 'Newest first',
    oldest: 'Oldest first',
    reset: 'Reset filters',
    empty: 'No transactions match these filters',
    dateError: 'The start date must not follow the end date.',
    count: 'Transactions found',
    note: 'Purchases are included in calculations. Other rows are form samples and do not affect the result.',
    sample: 'Form sample · excluded from the result',
    actual: 'Teaching purchase · included in calculations',
    transaction: 'Transaction',
    amount: 'Amount',
    spent: 'Spent',
    received: 'Received',
    source: 'Record source',
    externalSource: 'External source',
    externalDestination: 'External destination',
    bank: 'Sample bank account',
    destination: 'Destination',
    comment: 'Note',
    example: 'Fictional example',
    deleteTitle: 'Delete transaction?',
    confirmDelete: 'I confirm deletion of this sample',
    deleteNote:
      'In a real ledger, this changes balances and the result. This prototype keeps the row.',
    displayed: 'Fixed samples are displayed',
    accounts: 'Accounts and groups',
    groupName: 'Crypto',
  },
} as const;

export const recordsCopy = (language: Language) => (language === 'ru' ? copy.ru : copy.en);
