import type { Language } from '../i18n.ts';

export const insightWords = (language: Language) => (language === 'ru' ? ru : en);
const ru = {
  reasons: 'Откуда взялся результат',
  reasonsNote:
    'Выбранные покупки: начальная цена и курс, совместный эффект отдельно. Не доходность всех денежных потоков.',
  price: 'Изменение цены',
  fx: 'Изменение курса',
  interaction: 'Совместный эффект',
  fees: 'Комиссии',
  total: 'Итого',
  composition: 'Состав портфеля',
  report: 'Отчёт по выбранным портфелям',
  period: 'Период операций',
  all: 'За всё время',
  year: '2026 год',
  quarter: 'III квартал 2026',
  reportNote: 'Пример отчёта. Период относится к операциям.',
  unrealized: 'Нереализованный результат',
  realized: 'Реализованный результат',
  income: 'Дивиденды и проценты',
  export: 'Экспорт отчёта',
  format: 'Формат',
  exportNote: 'Это предпросмотр: файл не создаётся.',
  exported: 'Пример экспорта готов. Файл не создан.',
  cash: 'Деньги и классы активов',
  balance: 'Денежный остаток',
  cashNote: 'Остатки-примеры. Операции не меняют расчёт.',
  opening: 'Задать начальный остаток',
  catalog: 'Каталог активов',
  stocks: 'Акции',
  funds: 'Фонды',
  bonds: 'Облигации',
  crypto: 'Криптовалюты',
  money: 'Деньги',
  catalogNote: 'Учебные инструменты, без биржевого поиска.',
  catalogSearch: 'Найти в каталоге',
  noMatch: 'В примере совпадений нет',
  units: 'Позиция',
  quote: 'Цена и источник',
  freshness: 'Фиксированная учебная котировка, без обновления',
  history: 'История позиции',
  graph: 'График цены: вымышленный пример',
  valuation: 'Ручная оценка',
  saveValuation: 'Сохранить оценку',
  showExport: 'Показать экспорт',
  resetSearch: 'Сбросить поиск',
  positions: 'Позиции на',
  transactions: 'Операции за период',
  valuationNote: 'Черновик не меняет текущую стоимость или графики.',
  amount: 'Цена за единицу, USD',
  assessed: 'Дата оценки',
  saved: 'Пример ручной оценки сохранён. Котировка не изменилась.',
  periodRows: 'Покупок в периоде',
  current: 'Текущая оценка',
  cost: 'Стоимость приобретения',
  quantity: 'Количество',
  save: 'Сохранить',
  cancel: 'Отменить',
  date: 'Дата',
  source: 'Источник оценки',
  sourceExample: 'Учебная котировка MultiTracker',
};
const en = {
  reasons: 'What contributed to the result',
  reasonsNote:
    'Selected purchases: initial price and exchange rate, with the combined effect separate. This is not a return on all cash flows.',
  price: 'Price change',
  fx: 'Exchange rate change',
  interaction: 'Combined effect',
  fees: 'Fees',
  total: 'Total',
  composition: 'Portfolio composition',
  report: 'Report for selected portfolios',
  period: 'Transaction period',
  all: 'All time',
  year: 'Year 2026',
  quarter: 'Q3 2026',
  reportNote: 'Sample report. The period applies to transactions.',
  unrealized: 'Unrealized result',
  realized: 'Realized result',
  income: 'Dividends and interest',
  export: 'Export report',
  format: 'Sample format',
  exportNote: 'Preview only: no file is created.',
  exported: 'Sample export ready. No file was created.',
  cash: 'Cash and asset classes',
  balance: 'Cash balance',
  cashNote: 'Sample balances. Transactions do not change the calculation.',
  opening: 'Set opening balance',
  catalog: 'Asset catalog',
  stocks: 'Stocks',
  funds: 'Funds',
  bonds: 'Bonds',
  crypto: 'Cryptocurrencies',
  money: 'Cash',
  catalogNote: 'Sample instruments, without a live market search.',
  catalogSearch: 'Search catalog',
  noMatch: 'No matches in this sample',
  units: 'Position',
  quote: 'Price and source',
  freshness: 'Fixed teaching quote, without updates',
  history: 'Position history',
  graph: 'Price chart: fictional sample',
  valuation: 'Manual valuation',
  saveValuation: 'Save valuation',
  showExport: 'Show export',
  resetSearch: 'Clear search',
  positions: 'Positions as of',
  transactions: 'Transactions during period',
  valuationNote: 'The draft changes neither current value nor charts.',
  amount: 'Unit price, USD',
  assessed: 'Valuation date',
  saved: 'Sample manual valuation saved. The quote is unchanged.',
  periodRows: 'Purchases during period',
  current: 'Current valuation',
  cost: 'Acquisition cost',
  quantity: 'Quantity',
  save: 'Save',
  cancel: 'Cancel',
  date: 'Date',
  source: 'Valuation source',
  sourceExample: 'MultiTracker teaching quote',
};
