export const syncText = {
  ru: {
    onlyDemo: 'Учебные устройства и версии. Данные не передаются в облако.',
    automatic: 'Автоматическая синхронизация',
    enabled: 'Автоматический режим включён только в макете.',
    disabled: 'Автоматический режим выключен. Синхронизация не выполнялась.',
    last: 'Последняя учебная синхронизация',
    never: 'Не запускалась',
    idle: 'Ожидание запуска',
    success: 'Учебная синхронизация завершена',
    error: 'Пример ошибки сети. Данные не переданы; локальная версия доступна.',
    manual: 'Запустить учебную синхронизацию',
    retry: 'Повторить учебную синхронизацию',
    simulate: 'Показать ошибку сети при запуске',
    devices: 'Устройства',
    desktop: 'Этот компьютер',
    mobile: 'Телефон-пример',
    current: 'Текущее учебное устройство',
    activity: 'Последняя активность: 30.09.2026 10:25 UTC',
    revoke: 'Отозвать доступ',
    revoked: 'Доступ отозван в примере',
    revokeTitle: 'Отозвать доступ телефона?',
    revokeInfo:
      'Учебный телефон перестанет отображаться активным. Реальных устройств и сеансов нет.',
    cancel: 'Отмена',
    conflict: 'Сравнение конфликтующих версий',
    local: 'Локальная версия',
    remote: 'Версия из облака, пример',
    field: 'Поле',
    name: 'Название портфеля',
    label: 'Метка',
    localName: 'Долгосрочный',
    remoteName: 'Основной',
    localLabel: 'Накопления',
    remoteLabel: 'Инвестиции',
    localTime: '30.09.2026 10:20 UTC',
    remoteTime: '30.09.2026 10:22 UTC',
    compare: 'Сравнить версии',
    choose: 'Выберите версию для учебного результата',
    confirm: 'Подтвердить выбор',
    selected: 'Выбрана версия',
    resolved: 'Конфликт разрешён в примере.',
    warning: 'Предпросмотр сравнивает только название и метку. Активы и операции не меняются.',
    more: 'Другие действия',
  },
  en: {
    onlyDemo: 'Sample devices and versions. No data is transferred to the cloud.',
    automatic: 'Automatic sync',
    enabled: 'Automatic mode enabled in the mockup only.',
    disabled: 'Automatic mode disabled. No sync was performed.',
    last: 'Last sample sync',
    never: 'Not started',
    idle: 'Waiting to start',
    success: 'Sample sync complete',
    error: 'Sample network error. No data transferred; local data remains available.',
    manual: 'Run sample sync',
    retry: 'Retry sample sync',
    simulate: 'Show a network error when starting',
    devices: 'Devices',
    desktop: 'This computer',
    mobile: 'Sample phone',
    current: 'Current sample device',
    activity: 'Last activity: 2026-09-30 10:25 UTC',
    revoke: 'Revoke access',
    revoked: 'Access revoked in the sample',
    revokeTitle: 'Revoke phone access?',
    revokeInfo: 'The sample phone will become inactive. There are no real devices or sessions.',
    cancel: 'Cancel',
    conflict: 'Conflicting version comparison',
    local: 'Local version',
    remote: 'Cloud version, sample',
    field: 'Field',
    name: 'Portfolio name',
    label: 'Label',
    localName: 'Long term',
    remoteName: 'Main',
    localLabel: 'Savings',
    remoteLabel: 'Investments',
    localTime: '2026-09-30 10:20 UTC',
    remoteTime: '2026-09-30 10:22 UTC',
    compare: 'Compare versions',
    choose: 'Choose a version for the sample result',
    confirm: 'Confirm selection',
    selected: 'Selected version',
    resolved: 'Conflict resolved in the sample.',
    warning: 'The preview compares name and label only. Holdings and activity stay unchanged.',
    more: 'Other actions',
  },
};
export type SyncWords = (typeof syncText)['ru'];
export type Version = 'local' | 'remote';
