export const syncText = {
  ru: {
    onlyDemo: 'Учебные устройства и версии. Данные не передаются в облако.',
    automatic: 'Автоматическая синхронизация',
    enabled: 'Автоматический режим включён только в макете.',
    disabled: 'Автоматический режим выключен. Синхронизация не выполнялась.',
    last: 'Последняя синхронизация',
    never: 'Не запускалась',
    idle: 'Ожидание запуска',
    success: 'Учебная синхронизация готова',
    error: 'Пример ошибки сети',
    manual: 'Запустить синхронизацию',
    retry: 'Повторить синхронизацию',
    simulate: 'Показать ошибку сети при запуске',
    devices: 'Устройства',
    desktop: 'Этот компьютер',
    mobile: 'Телефон',
    current: 'Текущее устройство',
    active: 'Активно',
    revokedLabel: 'Отозвано',
    activity: 'Последняя активность: 30.09.2026 10:25 UTC',
    revoke: 'Отозвать доступ',
    revoked: 'Доступ отозван в примере',
    revokedDetail: 'Доступ отозван в примере. Настройки и история не изменялись.',
    cancel: 'Отмена',
    conflict: 'Сравнение конфликтующих версий',
    local: 'Локальная версия',
    remote: 'Версия из облака',
    field: 'Поле',
    name: 'Название портфеля',
    label: 'Метка',
    localName: 'Долгосрочный',
    remoteName: 'Основной',
    localLabel: 'Накопления',
    remoteLabel: 'Инвестиции',
    localTime: '30.09.2026 10:20 UTC',
    remoteTime: '30.09.2026 10:22 UTC',
    compare: 'Сравнить версии',
    choose: 'Выберите версию',
    confirm: 'Подтвердить выбор',
    selected: 'Выбрана версия',
    resolved: 'Конфликт разрешён в примере.',
    warning: 'Предпросмотр сравнивает только название и метку. Активы и операции не меняются.',
    mode: 'Режим синхронизации',
  },
  en: {
    onlyDemo: 'Sample devices and versions. No data is transferred to the cloud.',
    automatic: 'Automatic sync',
    enabled: 'Automatic mode enabled in the mockup only.',
    disabled: 'Automatic mode disabled. No sync was performed.',
    last: 'Last sync',
    never: 'Not started',
    idle: 'Waiting to start',
    success: 'Sample sync complete',
    error: 'Sample network error',
    manual: 'Run sync',
    retry: 'Retry sync',
    simulate: 'Show a network error when starting',
    devices: 'Devices',
    desktop: 'This computer',
    mobile: 'Phone',
    current: 'Current device',
    active: 'Active',
    revokedLabel: 'Revoked',
    activity: 'Last activity: 2026-09-30 10:25 UTC',
    revoke: 'Revoke access',
    revoked: 'Access revoked in the sample',
    revokedDetail: 'Access revoked in the sample. Settings and history are unchanged.',
    cancel: 'Cancel',
    conflict: 'Conflicting version comparison',
    local: 'Local version',
    remote: 'Cloud version',
    field: 'Field',
    name: 'Portfolio name',
    label: 'Label',
    localName: 'Long term',
    remoteName: 'Main',
    localLabel: 'Savings',
    remoteLabel: 'Investments',
    localTime: '2026-09-30 10:20 UTC',
    remoteTime: '2026-09-30 10:22 UTC',
    compare: 'Compare versions',
    choose: 'Choose a version',
    confirm: 'Confirm selection',
    selected: 'Selected version',
    resolved: 'Conflict resolved in the sample.',
    warning: 'The preview compares name and label only. Holdings and activity stay unchanged.',
    mode: 'Sync mode',
  },
};
export type SyncWords = (typeof syncText)['ru'];
export type Version = 'local' | 'remote';
