import type { Language } from '../i18n.ts';
export const formCopy = {
  ru: {
    account: 'Счёт списания / зачисления',
    targetAccount: 'Счёт получателя',
    priceCurrency: 'Валюта цены',
    feeCurrency: 'Валюта комиссии',
    receivedAmount: 'Полученная сумма',
    external: 'Внешняя сторона',
    externalSource: 'Внешний источник',
    externalDestination: 'Внешнее назначение',
    externalError:
      'Введите учебное название от 1 до 120 символов. Не вводите настоящие адреса и реквизиты.',
    type: 'Тип операции',
    portfolioId: 'Портфель / счёт',
    asset: 'Актив',
    quantity: 'Количество / коэффициент',
    price: 'Цена за единицу',
    amount: 'Сумма в выбранной валюте',
    fee: 'Комиссия в валюте операции',
    fx: 'Курс: RUB за 1 USD',
    date: 'Дата операции',
    targetPortfolio: 'Портфель / счёт получателя',
    currency: 'Валюта операции',
    targetCurrency: 'Получаемая валюта',
    note: 'Описание действия (например, дробление 2:1)',
    limits:
      'Количество до 1 млн, цена до 10 млн, сумма до 1 млрд, курс до 10 000. Валюты цены и комиссии выбираются отдельно.',
    title: 'Добавить операцию',
    noteSample:
      'Сохранение закрывает форму. Фиксированные остатки и результат примера не меняются.',
    positive:
      'Введите число в пределах макета: положительное; комиссия и начальный остаток могут быть нулевыми.',
    quantityError: 'Введите количество больше 0',
    priceError: 'Введите цену больше 0',
    rangeError: 'Слишком большое значение для макета',
    dateError: 'Выберите существующую дату с 01.01.2000 до 30.09.2026.',
    selectionError: 'Выберите подходящее значение из списка.',
    destination: 'Получатель должен отличаться от источника.',
    currencyError: 'Для обмена выберите разные валюты.',
    noteError: 'Опишите действие: от 1 до 200 символов.',
    entity: { portfolio: 'портфель', account: 'счёт', group: 'группу' },
    action: { create: 'Создать', edit: 'Изменить', archive: 'Архивировать', delete: 'Удалить' },
    entityName: 'Название',
    groupPortfolios: 'Портфели группы',
    accountKind: 'Тип счёта',
    broker: 'Брокерский',
    exchange: 'Биржевой',
    bank: 'Банковский',
    wallet: 'Кошелёк',
    confirmation: 'Подтверждаю действие с демонстрационным примером',
    confirmError: 'Подтвердите действие перед продолжением.',
    archiveNote: 'Архив скрывает объект и сохраняет историю. Здесь показано только подтверждение.',
    deleteNote: 'Удаление затронет записи. В макете данные остаются прежними.',
  },
  en: {
    account: 'Source / receiving account',
    targetAccount: 'Receiving account',
    priceCurrency: 'Price currency',
    feeCurrency: 'Fee currency',
    receivedAmount: 'Received amount',
    external: 'External party',
    externalSource: 'External source',
    externalDestination: 'External destination',
    externalError:
      'Enter a sample name from 1 to 120 characters. Do not enter real addresses or account details.',
    type: 'Transaction type',
    portfolioId: 'Portfolio / account',
    asset: 'Asset',
    quantity: 'Quantity / ratio',
    price: 'Unit price',
    amount: 'Amount in selected currency',
    fee: 'Fee in transaction currency',
    fx: 'Rate: RUB per 1 USD',
    date: 'Transaction date',
    targetPortfolio: 'Receiving portfolio / account',
    currency: 'Transaction currency',
    targetCurrency: 'Received currency',
    note: 'Action description (for example, split 2:1)',
    limits:
      'Quantity up to 1 million, price up to 10 million, amount up to 1 billion, rate up to 10,000. Price and fee currencies are selected separately.',
    title: 'Add transaction',
    noteSample: 'Saving closes the form. Fixed sample balances and results remain unchanged.',
    positive:
      'Enter a positive number within prototype limits. Fees and opening balances may be zero.',
    quantityError: 'Enter a quantity above 0',
    priceError: 'Enter a price above 0',
    rangeError: 'Value is too large for the prototype',
    dateError: 'Choose a valid date from Jan 1, 2000 to Sep 30, 2026.',
    selectionError: 'Choose a valid option from the list.',
    destination: 'The receiving account must differ from the source.',
    currencyError: 'Select different currencies for an exchange.',
    noteError: 'Describe the action using 1 to 200 characters.',
    entity: { portfolio: 'portfolio', account: 'account', group: 'group' },
    action: { create: 'Create', edit: 'Edit', archive: 'Archive', delete: 'Delete' },
    entityName: 'Name',
    groupPortfolios: 'Group portfolios',
    accountKind: 'Account type',
    broker: 'Brokerage',
    exchange: 'Exchange',
    bank: 'Bank',
    wallet: 'Wallet',
    confirmation: 'I confirm this action on the demonstration sample',
    confirmError: 'Confirm the action before continuing.',
    archiveNote: 'Archiving hides the item and retains history. This is a confirmation preview.',
    deleteNote: 'Deletion affects the records. Prototype data stays unchanged.',
  },
} as const;
export const getFormCopy = (language: Language) => (language === 'ru' ? formCopy.ru : formCopy.en);
