import type { Language } from '../i18n.ts';

const words = {
  ru: {
    title: 'Аналитика',
    subtitle: 'Понять результат и структуру',
    disclosure: 'Вымышленные примеры, отдельно от вашего портфеля. Не рекомендация.',
    analysis: 'Выберите анализ',
    period: 'Период',
    month: 'Сентябрь 2026',
    quarter: 'III квартал 2026',
    year: '2026 до сентября',
    performance: 'Доходность',
    allocation: 'Состав портфеля',
    fees: 'Комиссии',
    risk: 'Риск и P/E',
    decisions: 'После сделки',
    comparison: 'Цены активов',
    about: 'О данных',
    explanation: 'Как читать этот пример',
    performanceHelp:
      'Стоимость меняется из-за результата и чистых взносов. Чистые потоки — взносы минус выводы; в этой сцене они приходят в конце периода. Доходность исключает эти потоки. Эталон — вымышленный широкий индекс, без комиссий. Это не точный расчёт доходности реальных операций.',
    allocationHelp:
      'Доли — независимый вымышленный средний состав за выбранный период. Класс описывает тип актива, сектор — деятельность, география — рынок экспозиции. Хранение показывает вид счёта; использование площадок — число сделок. Эти срезы не измеряют риск сами по себе.',
    feesHelp:
      'Пример суммы комиссий выбранного периода: сделки, хранение и сеть. Сравнивать площадки по одной сумме нельзя: объём и число операций различаются. Налоги и скрытые спреды не включены.',
    riskHelp:
      'Бета сравнивает колебания с вымышленным эталоном; выше единицы означает более сильную историческую чувствительность. Отношение цены к прибыли (P/E) сравнивает цену акции с прибылью на акцию. Для убыточной компании и криптоактива показатель неприменим. Будущий результат из этих примеров не следует.',
    decisionsHelp:
      'Удачное и неудачное решение названы по последующему вымышленному результату. Это оценка задним числом, а не правило выбора сделок. Статистика охватывает только закрытые сделки, результат указан после комиссий, до налогов.',
    comparisonHelp:
      'Выберите от одного до четырёх активов. Сравнивается вымышленная история стоимости одной единицы, а не доходность равного вложения. У разных единиц разная цена; это не рейтинг привлекательности.',
    baseNote: 'История стоимости и потоки — в базовой валюте',
    displayNote: 'Комиссии и сравнение стоимости — в валюте показа',
    conversion: 'Все денежные примеры заданы в USD; фиксированный учебный USD/RUB',
    history: 'История стоимости и чистых потоков',
    day: 'Дата',
    worth: 'Стоимость',
    flows: 'Чистые потоки с начала периода',
    portfolio: 'Портфель',
    benchmark: 'Вымышленный широкий индекс',
    return: 'Доходность без потоков',
    result: 'Результат без потоков',
    data: 'Таблица значений графика',
    hidden: 'Финансовые значения и график скрыты',
    slice: 'Срез распределения',
    class: 'Класс активов',
    sector: 'Сектор',
    geography: 'География',
    location: 'Место хранения',
    exchange: 'Использование площадок',
    snapshot: 'Вымышленный средний состав за период',
    category: 'Категория',
    share: 'Доля стоимости',
    platform: 'Площадка',
    trades: 'Сделки',
    custody: 'Хранение',
    network: 'Сеть',
    total: 'Всего',
    metric: 'Показатель',
    beta: 'Бета вымышленного портфеля',
    pe: 'P/E выбранного учебного актива',
    unavailable: 'P/E криптоактива / убыточной компании',
    notApplicable: 'Неприменим',
    riskBasis:
      'Бета — отдельная вымышленная оценка по дневным наблюдениям выбранного периода. P/E — средняя оценка за период. Это иллюстрация систематического риска, а не полного риска или прогноза. Реальному портфелю не хватает истории и данных о прибыли; эти показатели для него не рассчитаны.',
    good: 'Удачное в этой сцене: продажа North',
    bad: 'Неудачное в этой сцене: продажа South',
    count: 'Закрытых сделок',
    win: 'Доля прибыльных сделок',
    average: 'Средний результат сделки',
    assets: 'Активы для сравнения',
    limit: 'До четырёх активов. Снимите выбор, чтобы добавить другой.',
    empty: 'Выберите хотя бы один актив для сравнения.',
    units: 'Учебное количество',
    comparisonDate: 'История стоимости учебной единицы',
    historyView: 'Вид истории',
    returns: 'Доходность и ориентиры',
    worthHistory: 'Стоимость и чистые вложения',
    flowHistory: 'Чистый денежный поток',
    results: 'Результат по активам',
    capital: 'Чистые вложения',
    realized: 'Реализованный результат',
    unrealized: 'Нереализованный результат',
    cost: 'Стоимость приобретения остатка',
    resultHelp:
      'Отдельная сцена: стоимость приобретения остатка включает комиссии. Реализованный результат — продажа минус затраты проданных единиц; нереализованный — оценка остатка минус его затраты. Метод затрат: первая купленная единица продаётся первой. Налоги не включены.',
    benchmarks: 'Ориентиры, до двух',
    secondBenchmark: 'Вымышленный облигационный индекс',
    size: 'Размер компаний',
    sizeUnavailable:
      'В этой сцене нет данных о капитализации компаний; распределение по размеру не рассчитано.',
    custodyView: 'Распределить хранение',
    bySource: 'По источнику',
    byAsset: 'По активу',
    accounts: 'Открыть счета',
    includedTrades: 'Учитываемые сделки',
    purchases: 'Покупки',
    sales: 'Продажи',
    allPlatforms: 'Все площадки',
    tradeNote: 'Только покупки и продажи. Переводы и пополнения не входят в число сделок.',
    popular: 'Наиболее частый актив',
    chooseDecision: 'Учебное решение',
    saleNorth: 'Продажа North',
    saleSouth: 'Продажа South',
    buyNorth: 'Покупка North',
    dealPrice: 'Цена сделки за единицу',
    laterPrice: 'Цена позже в этой сцене',
    laterChange: 'Изменение после сделки',
    peAsset: 'Актив для P/E',
    companyNorth: 'Прибыльная компания North',
    companySouth: 'Убыточная компания South',
    crypto: 'Криптоактив Beacon',
    peUnavailable:
      'P/E не применим: у South отрицательная прибыль, а Beacon не является акцией компании.',
    unitNote: 'Исходная единица всех комиссий в этой сцене — USD; токенных комиссий нет.',
    goodDecision: 'Удачное по последующей цене в этой сцене',
    badDecision: 'Неудачное по последующей цене в этой сцене',
    statistics:
      'Число покупок и продаж — из списка ниже; результат закрытых сделок — отдельный вымышленный пример.',
    performanceQuestion: 'Как изменился результат?',
    allocationQuestion: 'Из чего состоит портфель?',
    feesQuestion: 'Сколько ушло на комиссии?',
    riskQuestion: 'Как портфель реагирует на рынок?',
    decisionsQuestion: 'Что изменилось после сделки?',
    comparisonQuestion: 'Как менялась цена единицы?',
    unitsHelp: 'Валюты и учебный курс',
    tradeStatistics: 'Статистика сделок',
    laterDate: 'Цена на 30 сентября 2026',
    selected: 'Выбрано активов',
    unitPrice: 'Цена за единицу',
    periodMonth: 'Сентябрь',
    periodQuarter: 'III квартал',
    periodYear: '2026',
  },
  en: {
    title: 'Analytics',
    subtitle: 'Understand results and structure',
    disclosure: 'Fictional examples, separate from your portfolio. Not investment advice.',
    analysis: 'Choose an analysis',
    period: 'Period',
    month: 'September 2026',
    quarter: 'Q3 2026',
    year: '2026 through September',
    performance: 'Returns',
    allocation: 'Allocation',
    fees: 'Fees',
    risk: 'Risk and P/E',
    decisions: 'After a trade',
    comparison: 'Asset prices',
    about: 'About the data',
    explanation: 'How to read this example',
    performanceHelp:
      'Value changes through returns and net contributions. Net flows are deposits minus withdrawals; in this scene they arrive at period end. Returns exclude these flows. The benchmark is a fictional broad index, without fees. This is not an accurate return calculation for real transactions.',
    allocationHelp:
      'Weights are an independent fictional average composition during the selected period. Class describes asset type, sector describes activity, and geography describes exposure. Custody shows account type; platform usage shows trade counts. These slices do not measure risk on their own.',
    feesHelp:
      'Sample fees during the selected period: trading, custody and network costs. A fee total alone cannot rank platforms: trading volume and transaction count differ. Taxes and hidden spreads are excluded.',
    riskHelp:
      'Beta compares movements with a fictional benchmark; above one means greater historical sensitivity. Price-to-earnings (P/E) compares a stock price with earnings per share. It does not apply to a loss-making company or cryptoasset. These examples do not predict future results.',
    decisionsHelp:
      'Good and bad decisions are named after their later fictional result. This is hindsight, not a trading rule. Statistics include closed trades only, after fees and before tax.',
    comparisonHelp:
      'Choose one to four assets. This compares fictional worth history of one unit, not the return on equal investments. Different units have different prices; this is not an attractiveness ranking.',
    baseNote: 'Value history and flows use base currency',
    displayNote: 'Fees and asset worth use display currency',
    conversion: 'All money samples are in USD; fixed teaching USD/RUB rate',
    history: 'Value and net flow history',
    day: 'Date',
    worth: 'Worth',
    flows: 'Net flows since period start',
    portfolio: 'Portfolio',
    benchmark: 'Fictional broad index',
    return: 'Return excluding flows',
    result: 'Result excluding flows',
    data: 'Chart values table',
    hidden: 'Financial values and chart hidden',
    slice: 'Allocation slice',
    class: 'Asset class',
    sector: 'Sector',
    geography: 'Geography',
    location: 'Custody location',
    exchange: 'Platform usage',
    snapshot: 'Fictional average composition during the period',
    category: 'Category',
    share: 'Share of value',
    platform: 'Platform',
    trades: 'Trading',
    custody: 'Custody',
    network: 'Network',
    total: 'Total',
    metric: 'Metric',
    beta: 'Fictional portfolio beta',
    pe: 'Selected sample asset P/E',
    unavailable: 'Crypto / loss-making company P/E',
    notApplicable: 'Not applicable',
    riskBasis:
      'Beta is a separate fictional estimate from daily observations during the selected period. P/E is an average valuation during the period. This illustrates systematic risk, not all risk or a forecast. The real portfolio lacks history and earnings data; these metrics have not been calculated for it.',
    good: 'Good in this scene: sold North',
    bad: 'Bad in this scene: sold South',
    count: 'Closed trades',
    win: 'Winning trade share',
    average: 'Average trade result',
    assets: 'Assets to compare',
    limit: 'Up to four assets. Deselect one to add another.',
    empty: 'Choose at least one asset to compare.',
    units: 'Quantity',
    comparisonDate: 'Sample unit worth history',
    historyView: 'History view',
    returns: 'Returns and benchmarks',
    worthHistory: 'Worth and net invested capital',
    flowHistory: 'Net cash flow',
    results: 'Results by asset',
    capital: 'Net invested capital',
    realized: 'Realized result',
    unrealized: 'Unrealized result',
    cost: 'Remaining acquisition cost',
    resultHelp:
      'Separate scene: remaining acquisition cost includes fees. Realized result is sale proceeds minus the cost of units sold; unrealized result is remaining valuation minus its cost. Cost method: first units bought are sold first. Taxes are excluded.',
    benchmarks: 'Benchmarks, up to two',
    secondBenchmark: 'Fictional bond index',
    size: 'Company size',
    sizeUnavailable:
      'This scene has no company market capitalization data; size allocation is not calculated.',
    custodyView: 'Group custody',
    bySource: 'By source',
    byAsset: 'By asset',
    accounts: 'Open accounts',
    includedTrades: 'Included trades',
    purchases: 'Purchases',
    sales: 'Sales',
    allPlatforms: 'All platforms',
    tradeNote: 'Purchases and sales only. Transfers and deposits do not count as trades.',
    popular: 'Most frequent asset',
    chooseDecision: 'Decision',
    saleNorth: 'Sold North',
    saleSouth: 'Sold South',
    buyNorth: 'Bought North',
    dealPrice: 'Trade unit price',
    laterPrice: 'Later price in this scene',
    laterChange: 'Change after trade',
    peAsset: 'Asset for P/E',
    companyNorth: 'Profitable company North',
    companySouth: 'Loss-making company South',
    crypto: 'Beacon cryptoasset',
    peUnavailable:
      'P/E does not apply: South has negative earnings and Beacon is not company stock.',
    unitNote: 'All original fees in this scene are in USD; there are no token-denominated fees.',
    goodDecision: 'Good by the later price in this scene',
    badDecision: 'Bad by the later price in this scene',
    statistics:
      'Purchase and sale counts come from the list below; closed trade results are a separate fictional example.',
    performanceQuestion: 'How did the result change?',
    allocationQuestion: 'What makes up the portfolio?',
    feesQuestion: 'How much went to fees?',
    riskQuestion: 'How does the portfolio react to the market?',
    decisionsQuestion: 'What changed after the trade?',
    comparisonQuestion: 'How did the unit price change?',
    unitsHelp: 'Currencies and teaching rate',
    tradeStatistics: 'Trade statistics',
    laterDate: 'Price on September 30, 2026',
    selected: 'Selected assets',
    unitPrice: 'Unit price',
    periodMonth: 'September',
    periodQuarter: 'Q3 2026',
    periodYear: '2026',
  },
} as const;

export const analyticsWords = (language: Language) => (language === 'ru' ? words.ru : words.en);
export const analyticsLabel = (language: Language, key: string) =>
  new Map(Object.entries(analyticsWords(language))).get(key) ?? key;
