import type { Language } from '../i18n.ts';
import type { AssetClass } from './data.ts';

const copy = {
  ru: {
    markets: 'Рынки',
    shortSample: 'Учебные данные · цены не обновляются',
    filters: 'Фильтры',
    find: 'Найти актив',
    deleteAlert: 'Удалить уведомление',
    deleteQuestion: 'Удалить это учебное правило из вкладки? Избранное не изменится.',
    saveChanges: 'Сохранить изменения',
    draft: 'Условие черновика',
    noDraft: 'Укажите порог цены выше нуля.',
    roundTheClock: 'Круглосуточный рынок · учебная оценка',
    chartData: 'Значения графика',
    noteTitle: 'Об учебных ценах',
    following: 'Избранное',
    sample: 'Вымышленные цены и изменения. Нет рыночных запросов и отправки уведомлений.',
    fixed: 'Цены за единицу · учебный курс 1 USD = 120 RUB',
    class: 'Класс активов',
    search: 'Название или символ',
    movers: 'Движение за день',
    activeMovers: 'Активные · изменение от 1%',
    sector: 'Сектор',
    technology: 'Технологии',
    other: 'Прочие',
    regular: 'Основная сессия',
    sessionSelect: 'Торговая сессия',
    sessionNote: '30 сентября 2026 · UTC · только учебная цена, исполнения сделок нет.',
    explanation: 'Почему изменилась цена',
    explanationStock:
      'Учебный сюжет: публикация квартального отчёта изменила спрос. Это вымышленное объяснение, а не установленная причина или прогноз.',
    explanationOther:
      'Учебный сюжет: изменение спроса повлияло на цену. Это вымышленное объяснение, а не установленная причина или прогноз.',
    source: 'Источник: фиксированный набор макета · 30 сентября 2026.',
    pointsNote:
      'Индексы измеряются в пунктах; валютный пересчёт и денежный порог к ним не применяются.',
    channel: 'Категория сообщения',
    categoryPrice: 'Изменение цены',
    categoryEvent: 'Событие',
    categoryRecap: 'Итог дня',
    preview: 'Показать пример сообщения',
    priceMessage:
      'Учебное сообщение: выбранный актив пересёк условный порог. Проверки реальной цены не было.',
    eventMessage: 'Учебное сообщение: опубликовано вымышленное событие компании.',
    recapMessage: 'Учебное сообщение: дневная сводка примера готова к чтению.',
    repeatingNote:
      'Повторный пример: сообщение при каждом новом пересечении порога, не чаще раза в час. Никакой проверки или отправки нет.',
    all: 'Все',
    up: 'Рост',
    down: 'Снижение',
    clear: 'Сбросить фильтры',
    empty: 'Подходящих активов нет. Измените поиск или сбросьте фильтры.',
    emptyFollowing: 'В избранном пока нет активов. Откройте актив в «Рынках» и добавьте его.',
    follow: 'В избранное',
    unfollow: 'Убрать из избранного',
    indices: 'Учебные индексы · пункты',
    price: 'Учебная цена',
    valuationDate: '30 сентября 2026 · пример',
    range: 'Диапазон за день',
    premarket: 'До открытия · пример',
    postmarket: 'После закрытия · пример',
    session: 'Для биржевых акций; остальные примеры — условная дневная сессия.',
    history: 'Вымышленная динамика',
    sampleRange: 'Диапазон примера',
    points: 'пункты',
    date: 'Дата / время',
    period: 'Период примера',
    day: 'День',
    month: 'Месяц',
    year: 'Год',
    alerts: 'Учебные уведомления о цене',
    newAlert: 'Создать уведомление',
    edit: 'Изменить',
    actions: 'Действия',
    editAlert: 'Изменить уведомление',
    pause: 'Приостановить',
    resume: 'Возобновить',
    remove: 'Удалить',
    paused: 'Приостановлено',
    active: 'Пример включён',
    noAlerts: 'Уведомлений нет. Создайте пример из сведений об активе.',
    threshold: 'Порог цены',
    direction: 'Условие',
    above: 'Выше',
    below: 'Ниже',
    frequency: 'Частота',
    once: 'Однократно',
    repeating: 'Повторять',
    invalid: 'Введите конечное положительное число, например 460.',
    alertNote:
      'Это только пример условия. Проверки цены и отправки сообщений нет; настройка остаётся в этой вкладке.',
    saved: 'Пример уведомления сохранён в этой вкладке. Сообщения не отправляются.',
    removed: 'Пример уведомления удалён из этой вкладки.',
    updated: 'Состояние учебного уведомления изменено.',
    cancel: 'Отменить',
    save: 'Сохранить пример',
  },
  en: {
    markets: 'Markets',
    shortSample: 'Sample data · prices do not update',
    filters: 'Filters',
    find: 'Find an asset',
    deleteAlert: 'Delete alert',
    deleteQuestion: 'Delete this sample rule from the tab? Following stays unchanged.',
    saveChanges: 'Save changes',
    draft: 'Draft condition',
    noDraft: 'Enter a price threshold above zero.',
    roundTheClock: 'Round-the-clock market · sample valuation',
    chartData: 'Chart values',
    noteTitle: 'About sample prices',
    following: 'Following',
    sample: 'Fictional prices and changes. No market requests or notifications are sent.',
    fixed: 'Unit prices · sample rate 1 USD = 120 RUB',
    class: 'Asset class',
    search: 'Name or symbol',
    movers: 'Daily movers',
    activeMovers: 'Active · change of at least 1%',
    sector: 'Sector',
    technology: 'Technology',
    other: 'Other',
    regular: 'Regular session',
    sessionSelect: 'Trading session',
    sessionNote: 'September 30, 2026 · UTC · sample price only, no trade execution.',
    explanation: 'Why the price changed',
    explanationStock:
      'Sample story: a quarterly report changed demand. This is a fictional explanation, not an established cause or forecast.',
    explanationOther:
      'Sample story: changing demand affected the price. This is a fictional explanation, not an established cause or forecast.',
    source: 'Source: fixed prototype fixtures · September 30, 2026.',
    pointsNote:
      'Indices are measured in points; currency conversion and monetary thresholds do not apply.',
    channel: 'Message category',
    categoryPrice: 'Price movement',
    categoryEvent: 'Event',
    categoryRecap: 'Daily recap',
    preview: 'Show sample message',
    priceMessage:
      'Sample message: the selected asset crossed an illustrative threshold. No real price was checked.',
    eventMessage: 'Sample message: a fictional company event was published.',
    recapMessage: 'Sample message: the illustrative daily recap is ready to read.',
    repeatingNote:
      'Repeating sample: a message for each new threshold crossing, at most once an hour. Nothing is checked or sent.',
    all: 'All',
    up: 'Gainers',
    down: 'Losers',
    clear: 'Clear filters',
    empty: 'No matching assets. Change the search or clear the filters.',
    emptyFollowing: 'No assets followed yet. Open an asset in Markets and follow it.',
    follow: 'Follow',
    unfollow: 'Unfollow',
    indices: 'Sample indices · points',
    price: 'Sample price',
    valuationDate: 'September 30, 2026 · sample',
    range: 'Daily range',
    premarket: 'Pre-market · sample',
    postmarket: 'After-hours · sample',
    session: 'For exchange-listed stocks; other samples use an illustrative daily session.',
    history: 'Fictional price history',
    sampleRange: 'Sample range',
    points: 'points',
    date: 'Date / time',
    period: 'Sample period',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    alerts: 'Sample price alerts',
    newAlert: 'Create alert',
    edit: 'Edit',
    actions: 'Actions',
    editAlert: 'Edit alert',
    pause: 'Pause',
    resume: 'Resume',
    remove: 'Delete',
    paused: 'Paused',
    active: 'Sample enabled',
    noAlerts: 'No alerts. Create a sample from asset details.',
    threshold: 'Price threshold',
    direction: 'Condition',
    above: 'Above',
    below: 'Below',
    frequency: 'Frequency',
    once: 'One-off',
    repeating: 'Repeating',
    invalid: 'Enter a finite positive number, for example 460.',
    alertNote:
      'This only previews a condition. Prices are not checked and messages are not sent; the setting stays in this tab.',
    saved: 'Sample alert saved in this tab. No messages are sent.',
    removed: 'Sample alert removed from this tab.',
    updated: 'Sample alert state changed.',
    cancel: 'Cancel',
    save: 'Save sample',
  },
} as const;
export const marketWords = (language: Language) => (language === 'ru' ? copy.ru : copy.en);

export function className(kind: AssetClass, language: Language) {
  const names = {
    all: ['Все классы', 'All classes'],
    stock: ['Акции', 'Stocks'],
    crypto: ['Криптовалюты', 'Crypto'],
    fund: ['Фонды', 'Funds'],
    bond: ['Облигации', 'Bonds'],
    commodity: ['Сырьё', 'Commodities'],
    forex: ['Валюты', 'Currencies'],
    index: ['Индексы', 'Indices'],
  } as const;
  return new Map(Object.entries(names)).get(kind)?.[language === 'ru' ? 0 : 1] ?? kind;
}
